### ISSUE TITLE
Where can I find IP(2014)'s Source Code?

### ISSUE THREAD

**Issue by aichilongxia** [ir-lab/intprim#1]
Hello,I met a problem when I reading your code. I can't find the source code about IP which proposed in 2014 by Heni Ben Amor? could you provide it? Great thanks!

**Comment by joe-campbell** [comment]
Hi, the source code from Heni's original 2014 paper was never publicly released and we are unable to do so now, apologies.

However, we will soon be releasing a (vastly) updated version of this library which supports new inference methods from ongoing research as well as existing ones from other works, e.g., Probabilistic Primitives with DTW, which makes it easier to run comparisons. Please keep an eye out!

**Comment by aichilongxia** [comment]
Thanks for your reply! I also found this problem that DTW needs to be applied in Promp because  it decide what H(t) is, I expect to see this library.

**Comment by joe-campbell** [comment]
Just to follow up, we have now (belatedly) released IntPrim v2. This includes ProMP with DTW.
